version: '3.7'

services:
  ghfunctions:
    container_name: ghfunctions
    image: mcr.microsoft.com/azure-functions/powershell:4-powershell7.2-core-tools
    networks:
      - ghlocalnet
    tty: true
    restart: always
    ports:
      - "7071:7071"
    depends_on:
      - ghpostgres
    environment:
      - PGSQLCONN=host=ghpostgres;port=5432;database=db;user id=dbuser;password=BB723117-3Edc-4629-94ba-D7d3143C0500!;
    volumes:
      - ..:/workspace:cached
    init: true
    entrypoint: ["/usr/bin/func","host","start","--powershell","--script-root","/workspace/functions","--verbose"]
    
  ghpostgres:
    container_name: ghpostgres
    ports:
      - "5432:5432"
    networks:
      - ghlocalnet
    image: postgres:latest
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=BB723117-3Edc-4629-94ba-D7d3143C0500!
    volumes:
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - /var/run/docker.sock:/var/run/docker-host.sock

networks:
  ghlocalnet: null