version: '3.7'

services:
  functions:
    container_name: functions
    image: mcr.microsoft.com/azure-functions/powershell:4-powershell7.2-core-tools
    tty: true
    restart: always
    depends_on:
      - postgres
    environment:
      - PGSQLCONN=host = localhost; port = 5432; database = db; user id = dbuser; password = BB723117-3Edc-4629-94ba-D7d3143C0500!;
    volumes:
      - ..:/workspace:cached
    init: true
    network_mode: service:postgres
    
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=BB723117-3Edc-4629-94ba-D7d3143C0500!
    volumes:
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - /var/run/docker.sock:/var/run/docker-host.sock